name: network_info_plus
publish_to: none
description: Flutter plugin for discovering information (e.g. WiFi details) of the network.
version: 4.0.2
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/network_info_plus/network_info_plus
issue_tracker: https://github.com/fluttercommunity/plus_plugins/labels/network_info_plus

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

flutter:
  plugin:
    platforms:
      android:
        package: dev.fluttercommunity.plus.network_info
        pluginClass: NetworkInfoPlusPlugin
      ios:
        pluginClass: FLTNetworkInfoPlusPlugin
      linux:
        dartPluginClass: NetworkInfoPlusLinuxPlugin
      macos:
        pluginClass: NetworkInfoPlusPlugin
      windows:
        dartPluginClass: NetworkInfoPlusWindowsPlugin
      web:
        pluginClass: NetworkInfoPlusWebPlugin
        fileName: src/network_info_plus_web.dart

dependencies:
  collection: ^1.17.0
  nm: ^0.5.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.9.1
  network_info_plus_platform_interface: 
    git: https://github.com/kumsumit/network_info_plus_platform_interface.git
  # win32 is compatible across v4 and v5 for Win32 only (not COM)
  win32: ">=4.0.0 <6.0.0"
  ffi: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  plugin_platform_interface: 
    git: https://github.com/kumsumit/plugin_platform_interface.git
  flutter_lints: 
    git: https://github.com/kumsumit/flutter_lints.git
